# See https://kylerobots.github.io/tutorials/Automatic_Documentation/ for more info.
name: Deploy documentation

on:
  push:
    branches:
      - 'main'
    
jobs:
  build-documentation:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run Doxygen
        uses: mattnotmitt/doxygen-action@v1.9.5
      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html/
          enable_jekyll: false
          force_orphan: true
          publish_branch: github-pages
