name: Run tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  run_tests:
    runs-on: ubuntu-latest
    container: debian:12-slim
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Update and upgrade
        run: |
          apt-get update
          apt-get upgrade -y
      - name: Install dependencies
        run: |
          chmod u+x .devcontainer/library-scripts/provide-dependencies-ci.sh
          .devcontainer/library-scripts/provide-dependencies-ci.sh
      - name: Build
        run: |
          cmake -S . -B build -DBUILD_TESTING=ON
          cmake --build build
      - name: Run tests
        run: |
          cd build
          make test
